dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: j3bRmmI8z5C8vOplYsWLIRrFUtIjxfdoqeXEWxQllAkbw7WbCyZrIvxbQAoXoIzmynqXZBSrbNA5mTwTR8CFBph3BxuuCg2naIFsW1EXyqw9F10UoLSai3Lm0cuouECFtR9dom14uWFCquc2kUq0r6zPuY21FE/2sSUl5nQiI9UrQ45Nq+OjRkI6sV/8v3kbzPynXC5OWJqGEBaERxyJyG/NtvLFUl9/rr6WNXncO8Lu9z0Swm1zngpSciDsMIg8ssBtspLdIGWC9MMiyBpyAQdyPTiN59Aj3wJqm8YO8rpsN7tTa9zyY0CTYP9BMery3GCh1D8ixqGDYRbodaytetadXd64AGD1nF1n1wIRV1tkiitlweO9n0qnozNWhgmVc6TQgevhXaPfkewkiYySrN2yT9xSNiLjJqTaw3aja0C/SaeFg313xYvEwEU3iQnx6LX+Urzt1e7ojIq+/ziwPhEWGglP7Ue9n9oFRDfu+sNDhUaUi0JS5AkfgtUtS5WFBNcpUKnAq+8AH03auILiq2+Z85ktsrHF3OkYpta+o9A4RUyAMBZXwJDJjm+Uj3ITlwmvT/dSJ7wG2xjTE1xs2nSQK5B+Yir84N+aAbfezlioGrUzCQKWxux4RDbBmolWsfQSvja9vYbGYETHU5XcpLtvE+LMBtaIn+RWq/Agmu4=
  - secure: DMcO+XgWPiNzG26PdHdX9pnehscv/s7v/OBcvMXTBheJIXeAPHMhzLWdNX46T2oSDTwRm+xDLKIIRZx3yaXoXsl0YSJ5aUiHrrUkUT2m0Iowq7ZLvuemb6rNW8ow2Q1CXMSTwr9Nqeej+w1ojzcRXWNWcrgl6yxYhcKvoy5p3aoBpWpbEZaDQc5J8LtsRGaDulAb6sovSCPHfpbxT8SufiA56cS1l4RX5it2Ru+xR+rFUmY0wa+5DkP8eGCDEBEjc6zP7grMb6seoO3kdzNR/Z5bDX+weyUcgs9nqGJgiMlo84oIbTmgz9jRIifiGq4O/jM5HBAefR053VtN0veLTClWh/PG4iLrmtNx2MtNxi5UGiHd7GzBybXbJm5O0WBVXKtJHy3rb9IpOnb71BJq6poNXRiQfhdPWjCA7Ue1OYH75ZqoqTy26kxkpi6OyzbtjQlFbe3Nmy/PPta1Dl+fuBHkCuT3NxCegL2NZJV/TERimkyMJrT73S9HGgUKM0yeKERykmpPDlBRju1pinLMkYAX7+LHeD2y+nInZ8ur5unjs2X+PixJhqrwQuI68GkdDAP/CwqwCntXVvBl2MEMnnMvNg68dWAEoPxJr1xaMKZaATt0a9hBXUVtLyDofknAxyZLJsJ14q0EDxTsLWn68GsGS1h6Etxs+qf3kwLgu+0=
  - secure: mz6O9SOCg1voqIJxnUIi8kIIIuknEVuGds5zqdlFkaZX6VOdE8Oor8M/8RIsfdurtHB9AZbMC1NAqpV8Mbniqjg49XAF3ZG1gGYbXQKNpgllnwygqriXqDjtjqtgvnUWWetLf02lf0f4D/29699S+iQIReBCH9ccw7j89VTqLMtWiKWzUW+O0V/sp/UI0o6pjMAKvHw3lmKyzoLNdEKKsj7XQBRuU4s1cIaoEq6KfB6q21pMBEurmActc209eBBfnOeDtmcWxXTnVFeQFqwney9KCmHy4PPdrYFd1j5yLSOqgluMST89epUM5t1HRHONXpu6j2MCoxOpWt4W7aYjZdhOgV+bpd2KtzR+DK8ajmVVYeHgwQIlAN/BLJEKai+1IgxNGa9kfkbZ7hOoJnvtxYni4UwSbCm7S7sIVwEgbkabBZltbN4Np7MTtccnoJ2EezPKzHfmKPNu09Q480zLCQTsbE4wm31ij3y9ydr3OiJ06km23zOns92LHXS2L0aOxP5i6ttJ+IKQ/1LUejZPf9gEyCxlejAtmd1gCx6Ex0ofkvc5g3Pu4ugtvPArRQSNVVDZeE7cbEScxzFHxLe/H8MVQWeK+dXBmEaDwPA9aYh4BNUbtAeNrbXYhpZ8zYGbi+1OG7n66PA1+DIPQZ7tOutrLPLItzXnTc5kJBLaIlc=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
